### ISSUE TITLE
activity流程怎么就讲解到一半

### ISSUE THREAD

**Issue by zhangchaojiong** [wmszhe/AndroidNotes#1]
> activity流程怎么就讲解到一半，后面还有如何通过IApplicationThread 这个接口 
> 
> 通过进程间通讯，回调到ActivityThread中的ApplicationThread，然后去执行Activty
> 
>  的Oncreate（）。。。

**Comment by zhangchaojiong** [comment]
> 还有一些Activity 的跳压栈问题

**Comment by xinanwe** [comment]
这个项目里的东西都是在网上搜集来的，挺乱的，你可以在网上查一下，应该有详细文章的
